server.port: 8888

# file: file:///Users/sun/MyStudyAndTest/Microservices/SpringCloudConfig/src/main/resources/config/someservice
file: classpath:/config/someservice-config-directory

spring:
  profiles.active: native
  cloud:
    config:
      server:
        native:
          searchLocations: ${file}